#ifndef RENDER_COLORS_H
#define RENDER_COLORS_H

/*Couleur par défaut d'un way */
#define DEFAULT_WAY_COLOR_RED 255
#define DEFAULT_WAY_COLOR_GREEN 255
#define DEFAULT_WAY_COLOR_BLUE 255

#define WAY_NAME_COLOR_R 0
#define WAY_NAME_COLOR_G 0
#define WAY_NAME_COLOR_B 0

#define MOTOR_WAY_COLOR_R 238
#define MOTOR_WAY_COLOR_G 129
#define MOTOR_WAY_COLOR_B 153

#define TRUNK_WAY_COLOR_R 253
#define TRUNK_WAY_COLOR_G 176
#define TRUNK_WAY_COLOR_B 145

#define PRIMARY_WAY_COLOR_R 252
#define PRIMARY_WAY_COLOR_G 222
#define PRIMARY_WAY_COLOR_B 153

#define SECONDARY_WAY_COLOR_R 240
#define SECONDARY_WAY_COLOR_G 255
#define SECONDARY_WAY_COLOR_B 182

#define TERTIARY_WAY_COLOR_R 255
#define TERTIARY_WAY_COLOR_G 255
#define TERTIARY_WAY_COLOR_B 0

#define UNCLASSIFIED_WAY_COLOR 0xffffffff

#define RESIDENTIAL_WAY_COLOR 0xffffffff

#define PEDESTRIAN_WAY_COLOR_R 230
#define PEDESTRIAN_WAY_COLOR_G 230
#define PEDESTRIAN_WAY_COLOR_B 250

#define FOOT_WAY_COLOR_R 255
#define FOOT_WAY_COLOR_G 99
#define FOOT_WAY_COLOR_B 71

#define CYCLE_WAY_COLOR_R 0
#define CYCLE_WAY_COLOR_G 0
#define CYCLE_WAY_COLOR_B 102

#define BUILDING_AREA_COLOR_R 191
#define BUILDING_AREA_COLOR_G 174
#define BUILDING_AREA_COLOR_B 174

#define WATERWAY_COLOR_R 0
#define WATERWAY_COLOR_G 153
#define WATERWAY_COLOR_B 255

#define LANDUSE_COLOR_R 50
#define LANDUSE_COLOR_G 205
#define LANDUSE_COLOR_B 50

#define LANDUSE_ALLOTMENTS_COLOR_R 184
#define LANDUSE_ALLOTMENTS_COLOR_G 134
#define LANDUSE_ALLOTMENTS_COLOR_B 11

#define LANDUSE_BASIN_COLOR_R 95
#define LANDUSE_BASIN_COLOR_G 158
#define LANDUSE_BASIN_COLOR_B 160

#define LANDUSE_BROWN_COLOR_R 139
#define LANDUSE_BROWN_COLOR_G 69
#define LANDUSE_BROWN_COLOR_B 19

#define LANDUSE_CEMETERY_COLOR_R 154
#define LANDUSE_CEMETERY_COLOR_G 205
#define LANDUSE_CEMETERY_COLOR_B 50

#define LANDUSE_COM_COLOR_R 255
#define LANDUSE_COM_COLOR_G 160
#define LANDUSE_COM_COLOR_B 122

#define LANDUSE_CONSERVATION_COLOR_R 173
#define LANDUSE_CONSERVATION_COLOR_G 257
#define LANDUSE_CONSERVATION_COLOR_B 47

#define LANDUSE_CONST_COLOR_R 182
#define LANDUSE_CONST_COLOR_G 182
#define LANDUSE_CONST_COLOR_B 144

#define LANDUSE_FARM_COLOR_R 249
#define LANDUSE_FARM_COLOR_G 232
#define LANDUSE_FARM_COLOR_B 203

#define LANDUSE_FARMYARD_COLOR_R 234
#define LANDUSE_FARMYARD_COLOR_G 204
#define LANDUSE_FARMYARD_COLOR_B 164

#define LANDUSE_FOREST_COLOR_R 157
#define LANDUSE_FOREST_COLOR_G 202
#define LANDUSE_FOREST_COLOR_B 138

#define LANDUSE_GARAGES_COLOR_R 222
#define LANDUSE_GARAGES_COLOR_G 221
#define LANDUSE_GARAGES_COLOR_B 204

#define LANDUSE_GRASS_COLOR_R 207
#define LANDUSE_GRASS_COLOR_G 237
#define LANDUSE_GRASS_COLOR_B 165

#define LANDUSE_GREENFIELD_COLOR_R 241
#define LANDUSE_GREENFIELD_COLOR_G 238
#define LANDUSE_GREENFIELD_COLOR_B 232

#define LANDUSE_GREENHOUSE_COLOR_R 249
#define LANDUSE_GREENHOUSE_COLOR_G 232
#define LANDUSE_GREENHOUSE_COLOR_B 203

#define LANDUSE_INDUSTRIAL_COLOR_R 230
#define LANDUSE_INDUSTRIAL_COLOR_G 209
#define LANDUSE_INDUSTRIAL_COLOR_B 227

#define LANDUSE_LANDFILL_COLOR_R 182
#define LANDUSE_LANDFILL_COLOR_G 182
#define LANDUSE_LANDFILL_COLOR_B 144

#define LANDUSE_MEADOW_COLOR_R 207
#define LANDUSE_MEADOW_COLOR_G 236
#define LANDUSE_MEADOW_COLOR_B 168

#define LANDUSE_MILIT_COLOR_R 244
#define LANDUSE_MILIT_COLOR_G 219
#define LANDUSE_MILIT_COLOR_B 213

#define LANDUSE_ORCHARD_COLOR_R 158
#define LANDUSE_ORCHARD_COLOR_G 220
#define LANDUSE_ORCHARD_COLOR_B 144

#define LANDUSE_QUARRY_COLOR_R 183
#define LANDUSE_QUARRY_COLOR_G 181
#define LANDUSE_QUARRY_COLOR_B 181

#define LANDUSE_RAILWAY_COLOR_R 230
#define LANDUSE_RAILWAY_COLOR_G 209
#define LANDUSE_RAILWAY_COLOR_B 127

#define LANDUSE_REACTION_COLOR_R 207
#define LANDUSE_REACTION_COLOR_G 237
#define LANDUSE_REACTION_COLOR_B 165

#define LANDUSE_RESERVOIR_COLOR_R 180
#define LANDUSE_RESERVOIR_COLOR_G 208
#define LANDUSE_RESERVOIR_COLOR_B 209

#define LANDUSE_RESIDENTIAL_COLOR_R 252
#define LANDUSE_RESIDENTIAL_COLOR_G 201
#define LANDUSE_RESIDENTIAL_COLOR_B 20

#define LANDUSE_RETAIL_COLOR_R 254
#define LANDUSE_RETAIL_COLOR_G 202
#define LANDUSE_RETAIL_COLOR_B 197

#define LANDUSE_VILLGREEN_COLOR_R 207
#define LANDUSE_VILLGREEN_COLOR_G 237
#define LANDUSE_VILLGREEN_COLOR_B 165

#define LANDUSE_VINEYARD_COLOR_R 152
#define LANDUSE_VINEYARD_COLOR_G 212
#define LANDUSE_VINEYARD_COLOR_B 138

#define LEISURE_DEFAULT_COLOR_R 207
#define LEISURE_DEFAULT_COLOR_G 236
#define LEISURE_DEFAULT_COLOR_B 168

#define LEISURE_PARK_COLOR_R 205
#define LEISURE_PARK_COLOR_G 247
#define LEISURE_PARK_COLOR_B 201

#define LEISURE_PITCH_COLOR_R 138
#define LEISURE_PITCH_COLOR_G 211
#define LEISURE_PITCH_COLOR_B 175

#define LEISURE_STADIUM_COLOR_R 35
#define LEISURE_STADIUM_COLOR_G 205
#define LEISURE_STADIUM_COLOR_B 152

#define LEISURE_TRACK_COLOR_R 189
#define LEISURE_TRACK_COLOR_G 227
#define LEISURE_TRACK_COLOR_B 203

#define STEP_WAY_COLOR_R 253
#define STEP_WAY_COLOR_G 215
#define STEP_WAY_COLOR_B 161

#define TRACK_WAY_COLOR_R 218
#define TRACK_WAY_COLOR_G 165
#define TRACK_WAY_COLOR_B 32

#define LIVING_STREET_COLOR_R 236
#define LIVING_STREET_COLOR_G 237
#define LIVING_STREET_COLOR_B 266 

#define NATURAL_WOOD_COLOR_R 145
#define NATURAL_WOOD_COLOR_G 216
#define NATURAL_WOOD_COLOR_B 137

#define NATURAL_HEALTH_COLOR_R 214
#define NATURAL_HEALTH_COLOR_G 217
#define NATURAL_HEALTH_COLOR_B 159

#define NATURAL_GRASSLAND_COLOR_R 198
#define NATURAL_GRASSLAND_COLOR_G 228
#define NATURAL_GRASSLAND_COLOR_B 180

#define NATURAL_SCREE_COLOR_R 228
#define NATURAL_SCREE_COLOR_G 221
#define NATURAL_SCREE_COLOR_B 212

#define NATURAL_BEACH_COLOR_R 250
#define NATURAL_BEACH_COLOR_G 255
#define NATURAL_BEACH_COLOR_B 163

#define BACKGROUND_COLOR_R 242
#define BACKGROUND_COLOR_G 239
#define BACKGROUND_COLOR_B 233

#endif