pr_book:
    resource: "@prBookBundle/Resources/config/routing.yml"
    prefix:   /

stat:
    resource: "@StatBundle/Resources/config/routing.yml"
    prefix:   /

pr_recrutement:
    resource: "@prRecrutementBundle/Resources/config/routing.yml"
    prefix:   /

s:
    resource: "@SBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
